// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageP.proto

#ifndef PROTOBUF_MessageP_2eproto__INCLUDED
#define PROTOBUF_MessageP_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageP_2eproto();
void protobuf_AssignDesc_MessageP_2eproto();
void protobuf_ShutdownFile_MessageP_2eproto();

class MessageP;

// ===================================================================

class MessageP : public ::google::protobuf::Message {
 public:
  MessageP();
  virtual ~MessageP();
  
  MessageP(const MessageP& from);
  
  inline MessageP& operator=(const MessageP& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageP& default_instance();
  
  void Swap(MessageP* other);
  
  // implements Message ----------------------------------------------
  
  MessageP* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageP& from);
  void MergeFrom(const MessageP& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string sender = 1;
  inline bool has_sender() const;
  inline void clear_sender();
  static const int kSenderFieldNumber = 1;
  inline const ::std::string& sender() const;
  inline void set_sender(const ::std::string& value);
  inline void set_sender(const char* value);
  inline void set_sender(const char* value, size_t size);
  inline ::std::string* mutable_sender();
  inline ::std::string* release_sender();
  
  // required string receiver = 2;
  inline bool has_receiver() const;
  inline void clear_receiver();
  static const int kReceiverFieldNumber = 2;
  inline const ::std::string& receiver() const;
  inline void set_receiver(const ::std::string& value);
  inline void set_receiver(const char* value);
  inline void set_receiver(const char* value, size_t size);
  inline ::std::string* mutable_receiver();
  inline ::std::string* release_receiver();
  
  // required int32 code = 3;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 3;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);
  
  // repeated string argument = 4;
  inline int argument_size() const;
  inline void clear_argument();
  static const int kArgumentFieldNumber = 4;
  inline const ::std::string& argument(int index) const;
  inline ::std::string* mutable_argument(int index);
  inline void set_argument(int index, const ::std::string& value);
  inline void set_argument(int index, const char* value);
  inline void set_argument(int index, const char* value, size_t size);
  inline ::std::string* add_argument();
  inline void add_argument(const ::std::string& value);
  inline void add_argument(const char* value);
  inline void add_argument(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& argument() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_argument();
  
  // @@protoc_insertion_point(class_scope:MessageP)
 private:
  inline void set_has_sender();
  inline void clear_has_sender();
  inline void set_has_receiver();
  inline void clear_has_receiver();
  inline void set_has_code();
  inline void clear_has_code();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* sender_;
  ::std::string* receiver_;
  ::google::protobuf::RepeatedPtrField< ::std::string> argument_;
  ::google::protobuf::int32 code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageP_2eproto();
  friend void protobuf_AssignDesc_MessageP_2eproto();
  friend void protobuf_ShutdownFile_MessageP_2eproto();
  
  void InitAsDefaultInstance();
  static MessageP* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageP

// required string sender = 1;
inline bool MessageP::has_sender() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageP::set_has_sender() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageP::clear_has_sender() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageP::clear_sender() {
  if (sender_ != &::google::protobuf::internal::kEmptyString) {
    sender_->clear();
  }
  clear_has_sender();
}
inline const ::std::string& MessageP::sender() const {
  return *sender_;
}
inline void MessageP::set_sender(const ::std::string& value) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  sender_->assign(value);
}
inline void MessageP::set_sender(const char* value) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  sender_->assign(value);
}
inline void MessageP::set_sender(const char* value, size_t size) {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  sender_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MessageP::mutable_sender() {
  set_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    sender_ = new ::std::string;
  }
  return sender_;
}
inline ::std::string* MessageP::release_sender() {
  clear_has_sender();
  if (sender_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sender_;
    sender_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string receiver = 2;
inline bool MessageP::has_receiver() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageP::set_has_receiver() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageP::clear_has_receiver() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageP::clear_receiver() {
  if (receiver_ != &::google::protobuf::internal::kEmptyString) {
    receiver_->clear();
  }
  clear_has_receiver();
}
inline const ::std::string& MessageP::receiver() const {
  return *receiver_;
}
inline void MessageP::set_receiver(const ::std::string& value) {
  set_has_receiver();
  if (receiver_ == &::google::protobuf::internal::kEmptyString) {
    receiver_ = new ::std::string;
  }
  receiver_->assign(value);
}
inline void MessageP::set_receiver(const char* value) {
  set_has_receiver();
  if (receiver_ == &::google::protobuf::internal::kEmptyString) {
    receiver_ = new ::std::string;
  }
  receiver_->assign(value);
}
inline void MessageP::set_receiver(const char* value, size_t size) {
  set_has_receiver();
  if (receiver_ == &::google::protobuf::internal::kEmptyString) {
    receiver_ = new ::std::string;
  }
  receiver_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MessageP::mutable_receiver() {
  set_has_receiver();
  if (receiver_ == &::google::protobuf::internal::kEmptyString) {
    receiver_ = new ::std::string;
  }
  return receiver_;
}
inline ::std::string* MessageP::release_receiver() {
  clear_has_receiver();
  if (receiver_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = receiver_;
    receiver_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required int32 code = 3;
inline bool MessageP::has_code() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageP::set_has_code() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageP::clear_has_code() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageP::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 MessageP::code() const {
  return code_;
}
inline void MessageP::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
}

// repeated string argument = 4;
inline int MessageP::argument_size() const {
  return argument_.size();
}
inline void MessageP::clear_argument() {
  argument_.Clear();
}
inline const ::std::string& MessageP::argument(int index) const {
  return argument_.Get(index);
}
inline ::std::string* MessageP::mutable_argument(int index) {
  return argument_.Mutable(index);
}
inline void MessageP::set_argument(int index, const ::std::string& value) {
  argument_.Mutable(index)->assign(value);
}
inline void MessageP::set_argument(int index, const char* value) {
  argument_.Mutable(index)->assign(value);
}
inline void MessageP::set_argument(int index, const char* value, size_t size) {
  argument_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MessageP::add_argument() {
  return argument_.Add();
}
inline void MessageP::add_argument(const ::std::string& value) {
  argument_.Add()->assign(value);
}
inline void MessageP::add_argument(const char* value) {
  argument_.Add()->assign(value);
}
inline void MessageP::add_argument(const char* value, size_t size) {
  argument_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MessageP::argument() const {
  return argument_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MessageP::mutable_argument() {
  return &argument_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageP_2eproto__INCLUDED
