# Makefile.in generated by automake 1.11.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/hop
pkgincludedir = $(includedir)/hop
pkglibdir = $(libdir)/hop
pkglibexecdir = $(libexecdir)/hop
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = hadl$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_hadl_OBJECTS = hadl-main.$(OBJEXT) \
	hadl-PortConfigProvided.$(OBJEXT) hadl-Configuration.$(OBJEXT) \
	hadl-ConnectableElement.$(OBJEXT) hadl-Component.$(OBJEXT) \
	hadl-PortConfigRequired.$(OBJEXT) hadl-Connector.$(OBJEXT) \
	hadl-RoleConfig.$(OBJEXT) hadl-Element.$(OBJEXT) \
	hadl-RoleConfigProvided.$(OBJEXT) \
	hadl-InterfaceComposant.$(OBJEXT) \
	hadl-RoleConfigRequired.$(OBJEXT) \
	hadl-InterfaceConfiguration.$(OBJEXT) hadl-Role.$(OBJEXT) \
	hadl-InterfaceConnector.$(OBJEXT) hadl-RoleProvided.$(OBJEXT) \
	hadl-Interface.$(OBJEXT) hadl-RoleRequired.$(OBJEXT) \
	hadl-PortComposant.$(OBJEXT) hadl-Service.$(OBJEXT) \
	hadl-PortComposantProvided.$(OBJEXT) \
	hadl-ServiceProvided.$(OBJEXT) \
	hadl-PortComposantRequired.$(OBJEXT) \
	hadl-ServiceRequired.$(OBJEXT) hadl-PortConfig.$(OBJEXT)
hadl_OBJECTS = $(am_hadl_OBJECTS)
am__DEPENDENCIES_1 =
hadl_DEPENDENCIES = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
SOURCES = $(hadl_SOURCES)
DIST_SOURCES = $(hadl_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/gwen/Programmation/cpp/HADL/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AUTOCONF = ${SHELL} /home/gwen/Programmation/cpp/HADL/missing --run autoconf
AUTOHEADER = ${SHELL} /home/gwen/Programmation/cpp/HADL/missing --run autoheader
AUTOMAKE = ${SHELL} /home/gwen/Programmation/cpp/HADL/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBJSONCPP_CFLAGS = -I/usr/include/jsoncpp  
LIBJSONCPP_LIBS = -ljsoncpp  
LIBOBJS = 
LIBS = 
LIBSIGC_CFLAGS = -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include  
LIBSIGC_LIBS = -lsigc-2.0  
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/gwen/Programmation/cpp/HADL/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = hop
PACKAGE_BUGREPORT = BUG-REPORT-ADDRESS
PACKAGE_NAME = FULL-PACKAGE-NAME
PACKAGE_STRING = FULL-PACKAGE-NAME VERSION
PACKAGE_TARNAME = full-package-name
PACKAGE_URL = 
PACKAGE_VERSION = VERSION
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 1
abs_builddir = /home/gwen/Programmation/cpp/HADL
abs_srcdir = /home/gwen/Programmation/cpp/HADL
abs_top_builddir = /home/gwen/Programmation/cpp/HADL
abs_top_srcdir = /home/gwen/Programmation/cpp/HADL
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/gwen/Programmation/cpp/HADL/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
hadl_LDADD = $(LIBJSONCPP_LIBS) $(LIBSIGC_LIBS) 
hadl_CPPFLAGS = $(LIBJSONCPP_CFLAGS) $(LIBSIGC_CFLAGS)
hadl_SOURCES = src/main.cpp \
				src/api/PortConfigProvided.cpp \
				src/api/Configuration.cpp \
				src/api/ConnectableElement.cpp \
				src/api/Component.cpp \
				src/api/PortConfigRequired.cpp \
				src/api/Connector.cpp \
				src/api/RoleConfig.cpp \
				src/api/Element.cpp \
				src/api/RoleConfigProvided.cpp \
				src/api/InterfaceComposant.cpp \
				src/api/RoleConfigRequired.cpp \
				src/api/InterfaceConfiguration.cpp \
				src/api/Role.cpp \
				src/api/InterfaceConnector.cpp \
				src/api/RoleProvided.cpp \
				src/api/Interface.cpp \
				src/api/RoleRequired.cpp \
				src/api/PortComposant.cpp \
				src/api/Service.cpp \
				src/api/PortComposantProvided.cpp \
				src/api/ServiceProvided.cpp \
				src/api/PortComposantRequired.cpp \
				src/api/ServiceRequired.cpp \
				src/api/PortConfig.cpp

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
hadl$(EXEEXT): $(hadl_OBJECTS) $(hadl_DEPENDENCIES) $(EXTRA_hadl_DEPENDENCIES) 
	@rm -f hadl$(EXEEXT)
	$(CXXLINK) $(hadl_OBJECTS) $(hadl_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/hadl-Component.Po
include ./$(DEPDIR)/hadl-Configuration.Po
include ./$(DEPDIR)/hadl-ConnectableElement.Po
include ./$(DEPDIR)/hadl-Connector.Po
include ./$(DEPDIR)/hadl-Element.Po
include ./$(DEPDIR)/hadl-Interface.Po
include ./$(DEPDIR)/hadl-InterfaceComposant.Po
include ./$(DEPDIR)/hadl-InterfaceConfiguration.Po
include ./$(DEPDIR)/hadl-InterfaceConnector.Po
include ./$(DEPDIR)/hadl-PortComposant.Po
include ./$(DEPDIR)/hadl-PortComposantProvided.Po
include ./$(DEPDIR)/hadl-PortComposantRequired.Po
include ./$(DEPDIR)/hadl-PortConfig.Po
include ./$(DEPDIR)/hadl-PortConfigProvided.Po
include ./$(DEPDIR)/hadl-PortConfigRequired.Po
include ./$(DEPDIR)/hadl-Role.Po
include ./$(DEPDIR)/hadl-RoleConfig.Po
include ./$(DEPDIR)/hadl-RoleConfigProvided.Po
include ./$(DEPDIR)/hadl-RoleConfigRequired.Po
include ./$(DEPDIR)/hadl-RoleProvided.Po
include ./$(DEPDIR)/hadl-RoleRequired.Po
include ./$(DEPDIR)/hadl-Service.Po
include ./$(DEPDIR)/hadl-ServiceProvided.Po
include ./$(DEPDIR)/hadl-ServiceRequired.Po
include ./$(DEPDIR)/hadl-main.Po

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

hadl-main.o: src/main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-main.o -MD -MP -MF $(DEPDIR)/hadl-main.Tpo -c -o hadl-main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp
	$(am__mv) $(DEPDIR)/hadl-main.Tpo $(DEPDIR)/hadl-main.Po
#	source='src/main.cpp' object='hadl-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp

hadl-main.obj: src/main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-main.obj -MD -MP -MF $(DEPDIR)/hadl-main.Tpo -c -o hadl-main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-main.Tpo $(DEPDIR)/hadl-main.Po
#	source='src/main.cpp' object='hadl-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`

hadl-PortConfigProvided.o: src/api/PortConfigProvided.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortConfigProvided.o -MD -MP -MF $(DEPDIR)/hadl-PortConfigProvided.Tpo -c -o hadl-PortConfigProvided.o `test -f 'src/api/PortConfigProvided.cpp' || echo '$(srcdir)/'`src/api/PortConfigProvided.cpp
	$(am__mv) $(DEPDIR)/hadl-PortConfigProvided.Tpo $(DEPDIR)/hadl-PortConfigProvided.Po
#	source='src/api/PortConfigProvided.cpp' object='hadl-PortConfigProvided.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortConfigProvided.o `test -f 'src/api/PortConfigProvided.cpp' || echo '$(srcdir)/'`src/api/PortConfigProvided.cpp

hadl-PortConfigProvided.obj: src/api/PortConfigProvided.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortConfigProvided.obj -MD -MP -MF $(DEPDIR)/hadl-PortConfigProvided.Tpo -c -o hadl-PortConfigProvided.obj `if test -f 'src/api/PortConfigProvided.cpp'; then $(CYGPATH_W) 'src/api/PortConfigProvided.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortConfigProvided.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-PortConfigProvided.Tpo $(DEPDIR)/hadl-PortConfigProvided.Po
#	source='src/api/PortConfigProvided.cpp' object='hadl-PortConfigProvided.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortConfigProvided.obj `if test -f 'src/api/PortConfigProvided.cpp'; then $(CYGPATH_W) 'src/api/PortConfigProvided.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortConfigProvided.cpp'; fi`

hadl-Configuration.o: src/api/Configuration.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Configuration.o -MD -MP -MF $(DEPDIR)/hadl-Configuration.Tpo -c -o hadl-Configuration.o `test -f 'src/api/Configuration.cpp' || echo '$(srcdir)/'`src/api/Configuration.cpp
	$(am__mv) $(DEPDIR)/hadl-Configuration.Tpo $(DEPDIR)/hadl-Configuration.Po
#	source='src/api/Configuration.cpp' object='hadl-Configuration.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Configuration.o `test -f 'src/api/Configuration.cpp' || echo '$(srcdir)/'`src/api/Configuration.cpp

hadl-Configuration.obj: src/api/Configuration.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Configuration.obj -MD -MP -MF $(DEPDIR)/hadl-Configuration.Tpo -c -o hadl-Configuration.obj `if test -f 'src/api/Configuration.cpp'; then $(CYGPATH_W) 'src/api/Configuration.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Configuration.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-Configuration.Tpo $(DEPDIR)/hadl-Configuration.Po
#	source='src/api/Configuration.cpp' object='hadl-Configuration.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Configuration.obj `if test -f 'src/api/Configuration.cpp'; then $(CYGPATH_W) 'src/api/Configuration.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Configuration.cpp'; fi`

hadl-ConnectableElement.o: src/api/ConnectableElement.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-ConnectableElement.o -MD -MP -MF $(DEPDIR)/hadl-ConnectableElement.Tpo -c -o hadl-ConnectableElement.o `test -f 'src/api/ConnectableElement.cpp' || echo '$(srcdir)/'`src/api/ConnectableElement.cpp
	$(am__mv) $(DEPDIR)/hadl-ConnectableElement.Tpo $(DEPDIR)/hadl-ConnectableElement.Po
#	source='src/api/ConnectableElement.cpp' object='hadl-ConnectableElement.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-ConnectableElement.o `test -f 'src/api/ConnectableElement.cpp' || echo '$(srcdir)/'`src/api/ConnectableElement.cpp

hadl-ConnectableElement.obj: src/api/ConnectableElement.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-ConnectableElement.obj -MD -MP -MF $(DEPDIR)/hadl-ConnectableElement.Tpo -c -o hadl-ConnectableElement.obj `if test -f 'src/api/ConnectableElement.cpp'; then $(CYGPATH_W) 'src/api/ConnectableElement.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/ConnectableElement.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-ConnectableElement.Tpo $(DEPDIR)/hadl-ConnectableElement.Po
#	source='src/api/ConnectableElement.cpp' object='hadl-ConnectableElement.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-ConnectableElement.obj `if test -f 'src/api/ConnectableElement.cpp'; then $(CYGPATH_W) 'src/api/ConnectableElement.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/ConnectableElement.cpp'; fi`

hadl-Component.o: src/api/Component.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Component.o -MD -MP -MF $(DEPDIR)/hadl-Component.Tpo -c -o hadl-Component.o `test -f 'src/api/Component.cpp' || echo '$(srcdir)/'`src/api/Component.cpp
	$(am__mv) $(DEPDIR)/hadl-Component.Tpo $(DEPDIR)/hadl-Component.Po
#	source='src/api/Component.cpp' object='hadl-Component.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Component.o `test -f 'src/api/Component.cpp' || echo '$(srcdir)/'`src/api/Component.cpp

hadl-Component.obj: src/api/Component.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Component.obj -MD -MP -MF $(DEPDIR)/hadl-Component.Tpo -c -o hadl-Component.obj `if test -f 'src/api/Component.cpp'; then $(CYGPATH_W) 'src/api/Component.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Component.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-Component.Tpo $(DEPDIR)/hadl-Component.Po
#	source='src/api/Component.cpp' object='hadl-Component.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Component.obj `if test -f 'src/api/Component.cpp'; then $(CYGPATH_W) 'src/api/Component.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Component.cpp'; fi`

hadl-PortConfigRequired.o: src/api/PortConfigRequired.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortConfigRequired.o -MD -MP -MF $(DEPDIR)/hadl-PortConfigRequired.Tpo -c -o hadl-PortConfigRequired.o `test -f 'src/api/PortConfigRequired.cpp' || echo '$(srcdir)/'`src/api/PortConfigRequired.cpp
	$(am__mv) $(DEPDIR)/hadl-PortConfigRequired.Tpo $(DEPDIR)/hadl-PortConfigRequired.Po
#	source='src/api/PortConfigRequired.cpp' object='hadl-PortConfigRequired.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortConfigRequired.o `test -f 'src/api/PortConfigRequired.cpp' || echo '$(srcdir)/'`src/api/PortConfigRequired.cpp

hadl-PortConfigRequired.obj: src/api/PortConfigRequired.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortConfigRequired.obj -MD -MP -MF $(DEPDIR)/hadl-PortConfigRequired.Tpo -c -o hadl-PortConfigRequired.obj `if test -f 'src/api/PortConfigRequired.cpp'; then $(CYGPATH_W) 'src/api/PortConfigRequired.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortConfigRequired.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-PortConfigRequired.Tpo $(DEPDIR)/hadl-PortConfigRequired.Po
#	source='src/api/PortConfigRequired.cpp' object='hadl-PortConfigRequired.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortConfigRequired.obj `if test -f 'src/api/PortConfigRequired.cpp'; then $(CYGPATH_W) 'src/api/PortConfigRequired.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortConfigRequired.cpp'; fi`

hadl-Connector.o: src/api/Connector.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Connector.o -MD -MP -MF $(DEPDIR)/hadl-Connector.Tpo -c -o hadl-Connector.o `test -f 'src/api/Connector.cpp' || echo '$(srcdir)/'`src/api/Connector.cpp
	$(am__mv) $(DEPDIR)/hadl-Connector.Tpo $(DEPDIR)/hadl-Connector.Po
#	source='src/api/Connector.cpp' object='hadl-Connector.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Connector.o `test -f 'src/api/Connector.cpp' || echo '$(srcdir)/'`src/api/Connector.cpp

hadl-Connector.obj: src/api/Connector.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Connector.obj -MD -MP -MF $(DEPDIR)/hadl-Connector.Tpo -c -o hadl-Connector.obj `if test -f 'src/api/Connector.cpp'; then $(CYGPATH_W) 'src/api/Connector.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Connector.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-Connector.Tpo $(DEPDIR)/hadl-Connector.Po
#	source='src/api/Connector.cpp' object='hadl-Connector.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Connector.obj `if test -f 'src/api/Connector.cpp'; then $(CYGPATH_W) 'src/api/Connector.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Connector.cpp'; fi`

hadl-RoleConfig.o: src/api/RoleConfig.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-RoleConfig.o -MD -MP -MF $(DEPDIR)/hadl-RoleConfig.Tpo -c -o hadl-RoleConfig.o `test -f 'src/api/RoleConfig.cpp' || echo '$(srcdir)/'`src/api/RoleConfig.cpp
	$(am__mv) $(DEPDIR)/hadl-RoleConfig.Tpo $(DEPDIR)/hadl-RoleConfig.Po
#	source='src/api/RoleConfig.cpp' object='hadl-RoleConfig.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-RoleConfig.o `test -f 'src/api/RoleConfig.cpp' || echo '$(srcdir)/'`src/api/RoleConfig.cpp

hadl-RoleConfig.obj: src/api/RoleConfig.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-RoleConfig.obj -MD -MP -MF $(DEPDIR)/hadl-RoleConfig.Tpo -c -o hadl-RoleConfig.obj `if test -f 'src/api/RoleConfig.cpp'; then $(CYGPATH_W) 'src/api/RoleConfig.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/RoleConfig.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-RoleConfig.Tpo $(DEPDIR)/hadl-RoleConfig.Po
#	source='src/api/RoleConfig.cpp' object='hadl-RoleConfig.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-RoleConfig.obj `if test -f 'src/api/RoleConfig.cpp'; then $(CYGPATH_W) 'src/api/RoleConfig.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/RoleConfig.cpp'; fi`

hadl-Element.o: src/api/Element.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Element.o -MD -MP -MF $(DEPDIR)/hadl-Element.Tpo -c -o hadl-Element.o `test -f 'src/api/Element.cpp' || echo '$(srcdir)/'`src/api/Element.cpp
	$(am__mv) $(DEPDIR)/hadl-Element.Tpo $(DEPDIR)/hadl-Element.Po
#	source='src/api/Element.cpp' object='hadl-Element.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Element.o `test -f 'src/api/Element.cpp' || echo '$(srcdir)/'`src/api/Element.cpp

hadl-Element.obj: src/api/Element.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Element.obj -MD -MP -MF $(DEPDIR)/hadl-Element.Tpo -c -o hadl-Element.obj `if test -f 'src/api/Element.cpp'; then $(CYGPATH_W) 'src/api/Element.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Element.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-Element.Tpo $(DEPDIR)/hadl-Element.Po
#	source='src/api/Element.cpp' object='hadl-Element.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Element.obj `if test -f 'src/api/Element.cpp'; then $(CYGPATH_W) 'src/api/Element.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Element.cpp'; fi`

hadl-RoleConfigProvided.o: src/api/RoleConfigProvided.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-RoleConfigProvided.o -MD -MP -MF $(DEPDIR)/hadl-RoleConfigProvided.Tpo -c -o hadl-RoleConfigProvided.o `test -f 'src/api/RoleConfigProvided.cpp' || echo '$(srcdir)/'`src/api/RoleConfigProvided.cpp
	$(am__mv) $(DEPDIR)/hadl-RoleConfigProvided.Tpo $(DEPDIR)/hadl-RoleConfigProvided.Po
#	source='src/api/RoleConfigProvided.cpp' object='hadl-RoleConfigProvided.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-RoleConfigProvided.o `test -f 'src/api/RoleConfigProvided.cpp' || echo '$(srcdir)/'`src/api/RoleConfigProvided.cpp

hadl-RoleConfigProvided.obj: src/api/RoleConfigProvided.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-RoleConfigProvided.obj -MD -MP -MF $(DEPDIR)/hadl-RoleConfigProvided.Tpo -c -o hadl-RoleConfigProvided.obj `if test -f 'src/api/RoleConfigProvided.cpp'; then $(CYGPATH_W) 'src/api/RoleConfigProvided.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/RoleConfigProvided.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-RoleConfigProvided.Tpo $(DEPDIR)/hadl-RoleConfigProvided.Po
#	source='src/api/RoleConfigProvided.cpp' object='hadl-RoleConfigProvided.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-RoleConfigProvided.obj `if test -f 'src/api/RoleConfigProvided.cpp'; then $(CYGPATH_W) 'src/api/RoleConfigProvided.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/RoleConfigProvided.cpp'; fi`

hadl-InterfaceComposant.o: src/api/InterfaceComposant.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-InterfaceComposant.o -MD -MP -MF $(DEPDIR)/hadl-InterfaceComposant.Tpo -c -o hadl-InterfaceComposant.o `test -f 'src/api/InterfaceComposant.cpp' || echo '$(srcdir)/'`src/api/InterfaceComposant.cpp
	$(am__mv) $(DEPDIR)/hadl-InterfaceComposant.Tpo $(DEPDIR)/hadl-InterfaceComposant.Po
#	source='src/api/InterfaceComposant.cpp' object='hadl-InterfaceComposant.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-InterfaceComposant.o `test -f 'src/api/InterfaceComposant.cpp' || echo '$(srcdir)/'`src/api/InterfaceComposant.cpp

hadl-InterfaceComposant.obj: src/api/InterfaceComposant.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-InterfaceComposant.obj -MD -MP -MF $(DEPDIR)/hadl-InterfaceComposant.Tpo -c -o hadl-InterfaceComposant.obj `if test -f 'src/api/InterfaceComposant.cpp'; then $(CYGPATH_W) 'src/api/InterfaceComposant.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/InterfaceComposant.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-InterfaceComposant.Tpo $(DEPDIR)/hadl-InterfaceComposant.Po
#	source='src/api/InterfaceComposant.cpp' object='hadl-InterfaceComposant.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-InterfaceComposant.obj `if test -f 'src/api/InterfaceComposant.cpp'; then $(CYGPATH_W) 'src/api/InterfaceComposant.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/InterfaceComposant.cpp'; fi`

hadl-RoleConfigRequired.o: src/api/RoleConfigRequired.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-RoleConfigRequired.o -MD -MP -MF $(DEPDIR)/hadl-RoleConfigRequired.Tpo -c -o hadl-RoleConfigRequired.o `test -f 'src/api/RoleConfigRequired.cpp' || echo '$(srcdir)/'`src/api/RoleConfigRequired.cpp
	$(am__mv) $(DEPDIR)/hadl-RoleConfigRequired.Tpo $(DEPDIR)/hadl-RoleConfigRequired.Po
#	source='src/api/RoleConfigRequired.cpp' object='hadl-RoleConfigRequired.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-RoleConfigRequired.o `test -f 'src/api/RoleConfigRequired.cpp' || echo '$(srcdir)/'`src/api/RoleConfigRequired.cpp

hadl-RoleConfigRequired.obj: src/api/RoleConfigRequired.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-RoleConfigRequired.obj -MD -MP -MF $(DEPDIR)/hadl-RoleConfigRequired.Tpo -c -o hadl-RoleConfigRequired.obj `if test -f 'src/api/RoleConfigRequired.cpp'; then $(CYGPATH_W) 'src/api/RoleConfigRequired.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/RoleConfigRequired.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-RoleConfigRequired.Tpo $(DEPDIR)/hadl-RoleConfigRequired.Po
#	source='src/api/RoleConfigRequired.cpp' object='hadl-RoleConfigRequired.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-RoleConfigRequired.obj `if test -f 'src/api/RoleConfigRequired.cpp'; then $(CYGPATH_W) 'src/api/RoleConfigRequired.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/RoleConfigRequired.cpp'; fi`

hadl-InterfaceConfiguration.o: src/api/InterfaceConfiguration.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-InterfaceConfiguration.o -MD -MP -MF $(DEPDIR)/hadl-InterfaceConfiguration.Tpo -c -o hadl-InterfaceConfiguration.o `test -f 'src/api/InterfaceConfiguration.cpp' || echo '$(srcdir)/'`src/api/InterfaceConfiguration.cpp
	$(am__mv) $(DEPDIR)/hadl-InterfaceConfiguration.Tpo $(DEPDIR)/hadl-InterfaceConfiguration.Po
#	source='src/api/InterfaceConfiguration.cpp' object='hadl-InterfaceConfiguration.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-InterfaceConfiguration.o `test -f 'src/api/InterfaceConfiguration.cpp' || echo '$(srcdir)/'`src/api/InterfaceConfiguration.cpp

hadl-InterfaceConfiguration.obj: src/api/InterfaceConfiguration.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-InterfaceConfiguration.obj -MD -MP -MF $(DEPDIR)/hadl-InterfaceConfiguration.Tpo -c -o hadl-InterfaceConfiguration.obj `if test -f 'src/api/InterfaceConfiguration.cpp'; then $(CYGPATH_W) 'src/api/InterfaceConfiguration.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/InterfaceConfiguration.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-InterfaceConfiguration.Tpo $(DEPDIR)/hadl-InterfaceConfiguration.Po
#	source='src/api/InterfaceConfiguration.cpp' object='hadl-InterfaceConfiguration.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-InterfaceConfiguration.obj `if test -f 'src/api/InterfaceConfiguration.cpp'; then $(CYGPATH_W) 'src/api/InterfaceConfiguration.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/InterfaceConfiguration.cpp'; fi`

hadl-Role.o: src/api/Role.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Role.o -MD -MP -MF $(DEPDIR)/hadl-Role.Tpo -c -o hadl-Role.o `test -f 'src/api/Role.cpp' || echo '$(srcdir)/'`src/api/Role.cpp
	$(am__mv) $(DEPDIR)/hadl-Role.Tpo $(DEPDIR)/hadl-Role.Po
#	source='src/api/Role.cpp' object='hadl-Role.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Role.o `test -f 'src/api/Role.cpp' || echo '$(srcdir)/'`src/api/Role.cpp

hadl-Role.obj: src/api/Role.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Role.obj -MD -MP -MF $(DEPDIR)/hadl-Role.Tpo -c -o hadl-Role.obj `if test -f 'src/api/Role.cpp'; then $(CYGPATH_W) 'src/api/Role.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Role.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-Role.Tpo $(DEPDIR)/hadl-Role.Po
#	source='src/api/Role.cpp' object='hadl-Role.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Role.obj `if test -f 'src/api/Role.cpp'; then $(CYGPATH_W) 'src/api/Role.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Role.cpp'; fi`

hadl-InterfaceConnector.o: src/api/InterfaceConnector.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-InterfaceConnector.o -MD -MP -MF $(DEPDIR)/hadl-InterfaceConnector.Tpo -c -o hadl-InterfaceConnector.o `test -f 'src/api/InterfaceConnector.cpp' || echo '$(srcdir)/'`src/api/InterfaceConnector.cpp
	$(am__mv) $(DEPDIR)/hadl-InterfaceConnector.Tpo $(DEPDIR)/hadl-InterfaceConnector.Po
#	source='src/api/InterfaceConnector.cpp' object='hadl-InterfaceConnector.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-InterfaceConnector.o `test -f 'src/api/InterfaceConnector.cpp' || echo '$(srcdir)/'`src/api/InterfaceConnector.cpp

hadl-InterfaceConnector.obj: src/api/InterfaceConnector.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-InterfaceConnector.obj -MD -MP -MF $(DEPDIR)/hadl-InterfaceConnector.Tpo -c -o hadl-InterfaceConnector.obj `if test -f 'src/api/InterfaceConnector.cpp'; then $(CYGPATH_W) 'src/api/InterfaceConnector.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/InterfaceConnector.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-InterfaceConnector.Tpo $(DEPDIR)/hadl-InterfaceConnector.Po
#	source='src/api/InterfaceConnector.cpp' object='hadl-InterfaceConnector.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-InterfaceConnector.obj `if test -f 'src/api/InterfaceConnector.cpp'; then $(CYGPATH_W) 'src/api/InterfaceConnector.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/InterfaceConnector.cpp'; fi`

hadl-RoleProvided.o: src/api/RoleProvided.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-RoleProvided.o -MD -MP -MF $(DEPDIR)/hadl-RoleProvided.Tpo -c -o hadl-RoleProvided.o `test -f 'src/api/RoleProvided.cpp' || echo '$(srcdir)/'`src/api/RoleProvided.cpp
	$(am__mv) $(DEPDIR)/hadl-RoleProvided.Tpo $(DEPDIR)/hadl-RoleProvided.Po
#	source='src/api/RoleProvided.cpp' object='hadl-RoleProvided.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-RoleProvided.o `test -f 'src/api/RoleProvided.cpp' || echo '$(srcdir)/'`src/api/RoleProvided.cpp

hadl-RoleProvided.obj: src/api/RoleProvided.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-RoleProvided.obj -MD -MP -MF $(DEPDIR)/hadl-RoleProvided.Tpo -c -o hadl-RoleProvided.obj `if test -f 'src/api/RoleProvided.cpp'; then $(CYGPATH_W) 'src/api/RoleProvided.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/RoleProvided.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-RoleProvided.Tpo $(DEPDIR)/hadl-RoleProvided.Po
#	source='src/api/RoleProvided.cpp' object='hadl-RoleProvided.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-RoleProvided.obj `if test -f 'src/api/RoleProvided.cpp'; then $(CYGPATH_W) 'src/api/RoleProvided.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/RoleProvided.cpp'; fi`

hadl-Interface.o: src/api/Interface.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Interface.o -MD -MP -MF $(DEPDIR)/hadl-Interface.Tpo -c -o hadl-Interface.o `test -f 'src/api/Interface.cpp' || echo '$(srcdir)/'`src/api/Interface.cpp
	$(am__mv) $(DEPDIR)/hadl-Interface.Tpo $(DEPDIR)/hadl-Interface.Po
#	source='src/api/Interface.cpp' object='hadl-Interface.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Interface.o `test -f 'src/api/Interface.cpp' || echo '$(srcdir)/'`src/api/Interface.cpp

hadl-Interface.obj: src/api/Interface.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Interface.obj -MD -MP -MF $(DEPDIR)/hadl-Interface.Tpo -c -o hadl-Interface.obj `if test -f 'src/api/Interface.cpp'; then $(CYGPATH_W) 'src/api/Interface.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Interface.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-Interface.Tpo $(DEPDIR)/hadl-Interface.Po
#	source='src/api/Interface.cpp' object='hadl-Interface.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Interface.obj `if test -f 'src/api/Interface.cpp'; then $(CYGPATH_W) 'src/api/Interface.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Interface.cpp'; fi`

hadl-RoleRequired.o: src/api/RoleRequired.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-RoleRequired.o -MD -MP -MF $(DEPDIR)/hadl-RoleRequired.Tpo -c -o hadl-RoleRequired.o `test -f 'src/api/RoleRequired.cpp' || echo '$(srcdir)/'`src/api/RoleRequired.cpp
	$(am__mv) $(DEPDIR)/hadl-RoleRequired.Tpo $(DEPDIR)/hadl-RoleRequired.Po
#	source='src/api/RoleRequired.cpp' object='hadl-RoleRequired.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-RoleRequired.o `test -f 'src/api/RoleRequired.cpp' || echo '$(srcdir)/'`src/api/RoleRequired.cpp

hadl-RoleRequired.obj: src/api/RoleRequired.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-RoleRequired.obj -MD -MP -MF $(DEPDIR)/hadl-RoleRequired.Tpo -c -o hadl-RoleRequired.obj `if test -f 'src/api/RoleRequired.cpp'; then $(CYGPATH_W) 'src/api/RoleRequired.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/RoleRequired.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-RoleRequired.Tpo $(DEPDIR)/hadl-RoleRequired.Po
#	source='src/api/RoleRequired.cpp' object='hadl-RoleRequired.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-RoleRequired.obj `if test -f 'src/api/RoleRequired.cpp'; then $(CYGPATH_W) 'src/api/RoleRequired.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/RoleRequired.cpp'; fi`

hadl-PortComposant.o: src/api/PortComposant.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortComposant.o -MD -MP -MF $(DEPDIR)/hadl-PortComposant.Tpo -c -o hadl-PortComposant.o `test -f 'src/api/PortComposant.cpp' || echo '$(srcdir)/'`src/api/PortComposant.cpp
	$(am__mv) $(DEPDIR)/hadl-PortComposant.Tpo $(DEPDIR)/hadl-PortComposant.Po
#	source='src/api/PortComposant.cpp' object='hadl-PortComposant.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortComposant.o `test -f 'src/api/PortComposant.cpp' || echo '$(srcdir)/'`src/api/PortComposant.cpp

hadl-PortComposant.obj: src/api/PortComposant.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortComposant.obj -MD -MP -MF $(DEPDIR)/hadl-PortComposant.Tpo -c -o hadl-PortComposant.obj `if test -f 'src/api/PortComposant.cpp'; then $(CYGPATH_W) 'src/api/PortComposant.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortComposant.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-PortComposant.Tpo $(DEPDIR)/hadl-PortComposant.Po
#	source='src/api/PortComposant.cpp' object='hadl-PortComposant.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortComposant.obj `if test -f 'src/api/PortComposant.cpp'; then $(CYGPATH_W) 'src/api/PortComposant.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortComposant.cpp'; fi`

hadl-Service.o: src/api/Service.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Service.o -MD -MP -MF $(DEPDIR)/hadl-Service.Tpo -c -o hadl-Service.o `test -f 'src/api/Service.cpp' || echo '$(srcdir)/'`src/api/Service.cpp
	$(am__mv) $(DEPDIR)/hadl-Service.Tpo $(DEPDIR)/hadl-Service.Po
#	source='src/api/Service.cpp' object='hadl-Service.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Service.o `test -f 'src/api/Service.cpp' || echo '$(srcdir)/'`src/api/Service.cpp

hadl-Service.obj: src/api/Service.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-Service.obj -MD -MP -MF $(DEPDIR)/hadl-Service.Tpo -c -o hadl-Service.obj `if test -f 'src/api/Service.cpp'; then $(CYGPATH_W) 'src/api/Service.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Service.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-Service.Tpo $(DEPDIR)/hadl-Service.Po
#	source='src/api/Service.cpp' object='hadl-Service.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-Service.obj `if test -f 'src/api/Service.cpp'; then $(CYGPATH_W) 'src/api/Service.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/Service.cpp'; fi`

hadl-PortComposantProvided.o: src/api/PortComposantProvided.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortComposantProvided.o -MD -MP -MF $(DEPDIR)/hadl-PortComposantProvided.Tpo -c -o hadl-PortComposantProvided.o `test -f 'src/api/PortComposantProvided.cpp' || echo '$(srcdir)/'`src/api/PortComposantProvided.cpp
	$(am__mv) $(DEPDIR)/hadl-PortComposantProvided.Tpo $(DEPDIR)/hadl-PortComposantProvided.Po
#	source='src/api/PortComposantProvided.cpp' object='hadl-PortComposantProvided.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortComposantProvided.o `test -f 'src/api/PortComposantProvided.cpp' || echo '$(srcdir)/'`src/api/PortComposantProvided.cpp

hadl-PortComposantProvided.obj: src/api/PortComposantProvided.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortComposantProvided.obj -MD -MP -MF $(DEPDIR)/hadl-PortComposantProvided.Tpo -c -o hadl-PortComposantProvided.obj `if test -f 'src/api/PortComposantProvided.cpp'; then $(CYGPATH_W) 'src/api/PortComposantProvided.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortComposantProvided.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-PortComposantProvided.Tpo $(DEPDIR)/hadl-PortComposantProvided.Po
#	source='src/api/PortComposantProvided.cpp' object='hadl-PortComposantProvided.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortComposantProvided.obj `if test -f 'src/api/PortComposantProvided.cpp'; then $(CYGPATH_W) 'src/api/PortComposantProvided.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortComposantProvided.cpp'; fi`

hadl-ServiceProvided.o: src/api/ServiceProvided.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-ServiceProvided.o -MD -MP -MF $(DEPDIR)/hadl-ServiceProvided.Tpo -c -o hadl-ServiceProvided.o `test -f 'src/api/ServiceProvided.cpp' || echo '$(srcdir)/'`src/api/ServiceProvided.cpp
	$(am__mv) $(DEPDIR)/hadl-ServiceProvided.Tpo $(DEPDIR)/hadl-ServiceProvided.Po
#	source='src/api/ServiceProvided.cpp' object='hadl-ServiceProvided.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-ServiceProvided.o `test -f 'src/api/ServiceProvided.cpp' || echo '$(srcdir)/'`src/api/ServiceProvided.cpp

hadl-ServiceProvided.obj: src/api/ServiceProvided.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-ServiceProvided.obj -MD -MP -MF $(DEPDIR)/hadl-ServiceProvided.Tpo -c -o hadl-ServiceProvided.obj `if test -f 'src/api/ServiceProvided.cpp'; then $(CYGPATH_W) 'src/api/ServiceProvided.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/ServiceProvided.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-ServiceProvided.Tpo $(DEPDIR)/hadl-ServiceProvided.Po
#	source='src/api/ServiceProvided.cpp' object='hadl-ServiceProvided.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-ServiceProvided.obj `if test -f 'src/api/ServiceProvided.cpp'; then $(CYGPATH_W) 'src/api/ServiceProvided.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/ServiceProvided.cpp'; fi`

hadl-PortComposantRequired.o: src/api/PortComposantRequired.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortComposantRequired.o -MD -MP -MF $(DEPDIR)/hadl-PortComposantRequired.Tpo -c -o hadl-PortComposantRequired.o `test -f 'src/api/PortComposantRequired.cpp' || echo '$(srcdir)/'`src/api/PortComposantRequired.cpp
	$(am__mv) $(DEPDIR)/hadl-PortComposantRequired.Tpo $(DEPDIR)/hadl-PortComposantRequired.Po
#	source='src/api/PortComposantRequired.cpp' object='hadl-PortComposantRequired.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortComposantRequired.o `test -f 'src/api/PortComposantRequired.cpp' || echo '$(srcdir)/'`src/api/PortComposantRequired.cpp

hadl-PortComposantRequired.obj: src/api/PortComposantRequired.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortComposantRequired.obj -MD -MP -MF $(DEPDIR)/hadl-PortComposantRequired.Tpo -c -o hadl-PortComposantRequired.obj `if test -f 'src/api/PortComposantRequired.cpp'; then $(CYGPATH_W) 'src/api/PortComposantRequired.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortComposantRequired.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-PortComposantRequired.Tpo $(DEPDIR)/hadl-PortComposantRequired.Po
#	source='src/api/PortComposantRequired.cpp' object='hadl-PortComposantRequired.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortComposantRequired.obj `if test -f 'src/api/PortComposantRequired.cpp'; then $(CYGPATH_W) 'src/api/PortComposantRequired.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortComposantRequired.cpp'; fi`

hadl-ServiceRequired.o: src/api/ServiceRequired.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-ServiceRequired.o -MD -MP -MF $(DEPDIR)/hadl-ServiceRequired.Tpo -c -o hadl-ServiceRequired.o `test -f 'src/api/ServiceRequired.cpp' || echo '$(srcdir)/'`src/api/ServiceRequired.cpp
	$(am__mv) $(DEPDIR)/hadl-ServiceRequired.Tpo $(DEPDIR)/hadl-ServiceRequired.Po
#	source='src/api/ServiceRequired.cpp' object='hadl-ServiceRequired.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-ServiceRequired.o `test -f 'src/api/ServiceRequired.cpp' || echo '$(srcdir)/'`src/api/ServiceRequired.cpp

hadl-ServiceRequired.obj: src/api/ServiceRequired.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-ServiceRequired.obj -MD -MP -MF $(DEPDIR)/hadl-ServiceRequired.Tpo -c -o hadl-ServiceRequired.obj `if test -f 'src/api/ServiceRequired.cpp'; then $(CYGPATH_W) 'src/api/ServiceRequired.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/ServiceRequired.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-ServiceRequired.Tpo $(DEPDIR)/hadl-ServiceRequired.Po
#	source='src/api/ServiceRequired.cpp' object='hadl-ServiceRequired.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-ServiceRequired.obj `if test -f 'src/api/ServiceRequired.cpp'; then $(CYGPATH_W) 'src/api/ServiceRequired.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/ServiceRequired.cpp'; fi`

hadl-PortConfig.o: src/api/PortConfig.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortConfig.o -MD -MP -MF $(DEPDIR)/hadl-PortConfig.Tpo -c -o hadl-PortConfig.o `test -f 'src/api/PortConfig.cpp' || echo '$(srcdir)/'`src/api/PortConfig.cpp
	$(am__mv) $(DEPDIR)/hadl-PortConfig.Tpo $(DEPDIR)/hadl-PortConfig.Po
#	source='src/api/PortConfig.cpp' object='hadl-PortConfig.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortConfig.o `test -f 'src/api/PortConfig.cpp' || echo '$(srcdir)/'`src/api/PortConfig.cpp

hadl-PortConfig.obj: src/api/PortConfig.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hadl-PortConfig.obj -MD -MP -MF $(DEPDIR)/hadl-PortConfig.Tpo -c -o hadl-PortConfig.obj `if test -f 'src/api/PortConfig.cpp'; then $(CYGPATH_W) 'src/api/PortConfig.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortConfig.cpp'; fi`
	$(am__mv) $(DEPDIR)/hadl-PortConfig.Tpo $(DEPDIR)/hadl-PortConfig.Po
#	source='src/api/PortConfig.cpp' object='hadl-PortConfig.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(hadl_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hadl-PortConfig.obj `if test -f 'src/api/PortConfig.cpp'; then $(CYGPATH_W) 'src/api/PortConfig.cpp'; else $(CYGPATH_W) '$(srcdir)/src/api/PortConfig.cpp'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
